DROP TABLE D_Item CASCADE CONSTRAINTS PURGE;
CREATE TABLE D_Item
 (
	ITEM_ID VARCHAR(50) NOT NULL,	
	ITEM_TYPE VARCHAR(50) NOT NULL,
	ITEM_NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PKEY_D_Item PRIMARY KEY (ITEM_ID)
);

DROP TABLE F_EquipmentMonthly CASCADE CONSTRAINTS PURGE;
CREATE TABLE F_EquipmentMonthly
 (
	PERIOD TIMESTAMP,	
	ITEM_ID VARCHAR(50) NOT NULL,	
	BOX_HANDLED INTEGER NOT NULL,	
	KWH_CONSUMPTION INTEGER NOT NULL,	
	KWH_REGENERATING INTEGER NOT NULL,	
	TOTAL_KWH INTEGER NOT NULL,	
	EQUIPMENT_HOUR FLOAT NOT NULL,
	OPERATION_HOUR FLOAT NOT NULL,	
	CORRECTIVE_MAINTENANCE FLOAT NOT NULL,	
	PREVENTIVE_MAINTENANCE FLOAT NOT NULL,	
	SHUTDOWN FLOAT NOT NULL,	
	ACCIDENT FLOAT NOT NULL,
	NUMBER_OF_BREAKDOWN FLOAT NOT NULL,
	TOTAL_HOUR FLOAT,
	EHRM FLOAT,
	BREAKDOWN FLOAT,
	TROUBLE_SHOOT FLOAT,
	FUEL_USED FLOAT
);

DROP TABLE F_EquipmentDaily CASCADE CONSTRAINTS PURGE;
CREATE TABLE F_EquipmentDaily
 (
	PERIOD TIMESTAMP,	
	ITEM_ID VARCHAR(50) NOT NULL,	
	EQUIPMENT_HOUR FLOAT NOT NULL,	
	CORRECTIVE_MAINTENANCE FLOAT NOT NULL,	
	PREVENTIVE_MAINTENANCE FLOAT NOT NULL,	
	SHUTDOWN FLOAT NOT NULL,	
	ACCIDENT FLOAT NOT NULL,	
	OPERATION_HOUR FLOAT NOT NULL
);

INSERT INTO D_Item VALUES('IT001', 'CTT', 'CTT101');
INSERT INTO D_Item VALUES('IT002', 'CTT', 'CTT102');
INSERT INTO D_Item VALUES('IT003', 'CTT', 'CTT103');
INSERT INTO D_Item VALUES('IT004', 'CTT', 'CTT104');
INSERT INTO D_Item VALUES('IT005', 'CTT', 'CTT105');
INSERT INTO D_Item VALUES('IT006', 'CTT', 'CTT106');
INSERT INTO D_Item VALUES('IT007', 'CTT', 'CTT107');
INSERT INTO D_Item VALUES('IT008', 'CTT', 'CTT108');
INSERT INTO D_Item VALUES('IT009', 'CTT', 'CTT109');
INSERT INTO D_Item VALUES('IT010', 'CTT', 'CTT110');
INSERT INTO D_Item VALUES('IT011', 'CTT', 'CTT111');
INSERT INTO D_Item VALUES('IT012', 'CTT', 'CTT112');
INSERT INTO D_Item VALUES('IT013', 'CTT', 'CTT113');
INSERT INTO D_Item VALUES('IT014', 'CTT', 'CTT114');
INSERT INTO D_Item VALUES('IT015', 'CTT', 'CTT115');
INSERT INTO D_Item VALUES('IT016', 'CTT', 'CTT116');
INSERT INTO D_Item VALUES('IT017', 'CTT', 'CTT117');
INSERT INTO D_Item VALUES('IT018', 'CTT', 'CTT118');
INSERT INTO D_Item VALUES('IT019', 'CTT', 'CTT119');
INSERT INTO D_Item VALUES('IT020', 'CTT', 'CTT120');
INSERT INTO D_Item VALUES('IT021', 'CTT', 'CTT121');
INSERT INTO D_Item VALUES('IT022', 'CTT', 'CTT122');
INSERT INTO D_Item VALUES('IT023', 'CTT', 'CTT123');
INSERT INTO D_Item VALUES('IT024', 'CTT', 'CTT124');
INSERT INTO D_Item VALUES('IT025', 'CTT', 'CTT125');
INSERT INTO D_Item VALUES('IT026', 'CTT', 'CTT126');
INSERT INTO D_Item VALUES('IT027', 'CTT', 'CTT127');
INSERT INTO D_Item VALUES('IT028', 'CTT', 'CTT128');
INSERT INTO D_Item VALUES('IT029', 'CTT', 'CTT129');
INSERT INTO D_Item VALUES('IT030', 'CTT', 'CTT130');
INSERT INTO D_Item VALUES('IT031', 'CTT', 'CTT131');
INSERT INTO D_Item VALUES('IT032', 'CTT', 'CTT132');
INSERT INTO D_Item VALUES('IT033', 'CTT', 'CTT133');
INSERT INTO D_Item VALUES('IT034', 'CTT', 'CTT134');
INSERT INTO D_Item VALUES('IT035', 'CTT', 'CTT135');
INSERT INTO D_Item VALUES('IT036', 'CTT', 'CTT136');
INSERT INTO D_Item VALUES('IT037', 'CTT', 'CTT137');
INSERT INTO D_Item VALUES('IT038', 'CTT', 'CTT138');
INSERT INTO D_Item VALUES('IT039', 'CTT', 'CTT139');
INSERT INTO D_Item VALUES('IT040', 'CTT', 'CTT140');
INSERT INTO D_Item VALUES('IT041', 'CTT', 'CTT141');
INSERT INTO D_Item VALUES('IT042', 'CTT', 'CTT142');
INSERT INTO D_Item VALUES('IT043', 'CTT', 'CTT143');
INSERT INTO D_Item VALUES('IT044', 'CTT', 'CTT144');
INSERT INTO D_Item VALUES('IT045', 'CTT', 'CTT145');
INSERT INTO D_Item VALUES('IT046', 'CTT', 'CTT146');
INSERT INTO D_Item VALUES('IT047', 'CTT', 'CTT147');
INSERT INTO D_Item VALUES('IT048', 'CTT', 'CTT148');
INSERT INTO D_Item VALUES('IT049', 'CTT', 'CTT149');
INSERT INTO D_Item VALUES('IT050', 'CTT', 'CTT150');
INSERT INTO D_Item VALUES('IT051', 'TerBerg', 'TerBerg 601');
INSERT INTO D_Item VALUES('IT052', 'TerBerg', 'TerBerg 602');
INSERT INTO D_Item VALUES('IT053', 'TerBerg', 'TerBerg 603');
INSERT INTO D_Item VALUES('IT054', 'TerBerg', 'TerBerg 604');
INSERT INTO D_Item VALUES('IT055', 'TerBerg', 'TerBerg 605');
INSERT INTO D_Item VALUES('IT056', 'TerBerg', 'TerBerg 606');
INSERT INTO D_Item VALUES('IT057', 'TerBerg', 'TerBerg 607');
INSERT INTO D_Item VALUES('IT058', 'TerBerg', 'TerBerg 608');
INSERT INTO D_Item VALUES('IT059', 'TerBerg', 'TerBerg 609');
INSERT INTO D_Item VALUES('IT060', 'TerBerg', 'TerBerg 610');
INSERT INTO D_Item VALUES('IT061', 'SC', 'SC 01');
INSERT INTO D_Item VALUES('IT062', 'SC', 'SC 02');
INSERT INTO D_Item VALUES('IT063', 'SC', 'SC 03');
INSERT INTO D_Item VALUES('IT064', 'SC', 'SC 04');
INSERT INTO D_Item VALUES('IT065', 'SC', 'SC 05');
INSERT INTO D_Item VALUES('IT066', 'RS KALMAR', 'RS KALMAR 01');
INSERT INTO D_Item VALUES('IT067', 'RS KALMAR', 'RS KALMAR 02');
INSERT INTO D_Item VALUES('IT068', 'RS KALMAR', 'RS KALMAR 03');
INSERT INTO D_Item VALUES('IT069', 'RS KALMAR', 'RS KALMAR 04');
INSERT INTO D_Item VALUES('IT070', 'EH', 'EH');
INSERT INTO D_Item VALUES('IT071', 'STS', 'STS 01I');
INSERT INTO D_Item VALUES('IT072', 'STS', 'STS 02I');
INSERT INTO D_Item VALUES('IT073', 'STS', 'STS 03I');
INSERT INTO D_Item VALUES('IT074', 'STS', 'STS 04I');
INSERT INTO D_Item VALUES('IT075', 'STS', 'STS 05I');
INSERT INTO D_Item VALUES('IT076', 'STS', 'STS 01D');
INSERT INTO D_Item VALUES('IT077', 'STS', 'STS 02D');
INSERT INTO D_Item VALUES('IT078', 'STS', 'STS 03D');
INSERT INTO D_Item VALUES('IT079', 'STS', 'STS 04D');
INSERT INTO D_Item VALUES('IT080', 'STS', 'STS 05D');
INSERT INTO D_Item VALUES('IT081', 'ASC', 'ASC 01L');
INSERT INTO D_Item VALUES('IT082', 'ASC', 'ASC 02L');
INSERT INTO D_Item VALUES('IT083', 'ASC', 'ASC 03L');
INSERT INTO D_Item VALUES('IT084', 'ASC', 'ASC 04L');
INSERT INTO D_Item VALUES('IT085', 'ASC', 'ASC 05L');
INSERT INTO D_Item VALUES('IT086', 'ASC', 'ASC 06L');
INSERT INTO D_Item VALUES('IT087', 'ASC', 'ASC 07L');
INSERT INTO D_Item VALUES('IT088', 'ASC', 'ASC 08L');
INSERT INTO D_Item VALUES('IT089', 'ASC', 'ASC 09L');
INSERT INTO D_Item VALUES('IT090', 'ASC', 'ASC 10L');
INSERT INTO D_Item VALUES('IT091', 'ASC', 'ASC 01W');
INSERT INTO D_Item VALUES('IT092', 'ASC', 'ASC 02W');
INSERT INTO D_Item VALUES('IT093', 'ASC', 'ASC 03W');
INSERT INTO D_Item VALUES('IT094', 'ASC', 'ASC 04W');
INSERT INTO D_Item VALUES('IT095', 'ASC', 'ASC 05W');
INSERT INTO D_Item VALUES('IT096', 'ASC', 'ASC 06W');
INSERT INTO D_Item VALUES('IT097', 'ASC', 'ASC 07W');
INSERT INTO D_Item VALUES('IT098', 'ASC', 'ASC 08W');
INSERT INTO D_Item VALUES('IT099', 'ASC', 'ASC 09W');
INSERT INTO D_Item VALUES('IT100', 'ASC', 'ASC 10W');
INSERT INTO D_Item VALUES('IT101', 'GSU', 'GSU 01');
INSERT INTO D_Item VALUES('IT102', 'GSU', 'GSU 02');
INSERT INTO D_Item VALUES('IT103', 'Conveyor', 'Conveyor');